---
# Site Settings

# SEO plugin
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# Site's title.
# Used as part of the title tag like "Home | Ben's Awesome Site".
title: Роман Николаев

# Global author information.
# See Advanced usage:
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
author: Роман Николаев

# A short description (e.g., A blog dedicated to reviewing cat gifs),
# used as part of the title tag like "Ben's Awesome Site | A blog dedicated to reviewing cat gifs"
# instead of "Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs"
# that would be used when page.title is not defined.
tagline: Team Lead & Site Reliability Engineer

# A longer description used for the description meta tag.
# Also used as fallback for pages that don't provide their own description,
# and also as part of the page's title tag if neither "page.title" nor "site.tagline"
# has been defined.
description: ""

# The full URL to your site.
# Note: site.github.url will be used by default.
url: https://nikolaev-rd.github.io

# Change it according to your repository name
baseurl: ""

# Specify social profiles.
# https://developers.google.com/search/docs/guides/enhance-site#add-your-sites-name-logo-and-social-links
social:
  links:
    - https://github.com/nikolaev-rd

# yamllint disable-line rule:comments
#twitter:
#  # The site's Twitter handle.
#  username: stevedoe123
#  # The site's default card type
#  card: summary

google_site_verification: ""  # Put your google verification tag here
# End SEO

# Style will be applied only after restarting the build or serve.
# Just choose one of the options:
# gray | blue | turquoise | green | berry | red
theme_skin: green

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

encoding: utf-8

# Build settings
compress-site: true

# http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Exclude these files from your production _site
exclude:
  - Gemfile*
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - docker-compose.yml
  - Dockerfile*
  - .env
