layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Monitoring
    web_url: https://github.com/topics/monitoring
   
  - name: Grafana
    web_url: https://github.com/topics/grafana
    image_url: https://raw.githubusercontent.com/nikolaev-rd/Zabbix-AlertScripts/master/_img/Grafana_logo_circle.png
  
  - name: Zabbix
    web_url: https://github.com/topics/zabbix
    image_url: https://avatars1.githubusercontent.com/u/4561226
    
  - name: Prometheus
    web_url: https://github.com/topics/prometheus
    image_url: https://raw.githubusercontent.com/prometheus/docs/master/static/prometheus_logo.png
    
  - name: Netdata
    web_url: https://github.com/topics/netdata
    image_url: https://raw.githubusercontent.com/netdata/netdata/master/web/gui/images/favicon-96x96.png
    
  - name: Graphite
    web_url: https://github.com/topics/graphite
    image_url: https://avatars0.githubusercontent.com/u/1714806
    
  - name: ElasticSearch
    web_url: https://github.com/topics/elasticsearch
    image_url: https://avatars0.githubusercontent.com/u/6764390
    
  - name: ClickHouse
    web_url: https://github.com/topics/clickhouse
    image_url: https://raw.githubusercontent.com/yandex/ClickHouse/master/website/images/logo.png
    
  - name: InfluxData
    web_url: https://github.com/topics/influxdata
    image_url: https://raw.githubusercontent.com/influxdata/docs.influxdata.com/master/static/img/influx-logo-cubo-dark.png
    
  - name: Loki
    web_url: https://github.com/topics/loki
    image_url: https://raw.githubusercontent.com/grafana/loki/master/docs/logo.png
    
  - name: StackStorm
    web_url: https://github.com/topics/stackstorm
    image_url: https://avatars1.githubusercontent.com/u/4969009
    
  - name: Ansible
    web_url: https://github.com/topics/ansible
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/ansible/ansible.png
    
  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/bash/bash.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
  
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/ccc16358ac4530c6a69b1b80c7223cd2744dea83/topics/php/php.png
  
  - name: PostgreSQL
    web_url: hhttps://github.com/topics/postgresql
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/postgresql/postgresql.png
    
theme: jekyll-theme-tactile
